package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class Sistemas extends javax.swing.JFrame {

    /**
     * Creates new form Sistemas
     */
    public Sistemas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilaFlorencia = new javax.swing.JLabel();
        PersonaFlorencia = new javax.swing.JLabel();
        TrenFlorencia = new javax.swing.JLabel();
        FilaVenicia = new javax.swing.JLabel();
        PersonasVenicia = new javax.swing.JLabel();
        TrenVenicia = new javax.swing.JLabel();
        FilaMilan = new javax.swing.JLabel();
        PersonasMilan = new javax.swing.JLabel();
        TrenMilan = new javax.swing.JLabel();
        FilaNapoles = new javax.swing.JLabel();
        PersonasNapoles = new javax.swing.JLabel();
        TrenNapoles = new javax.swing.JLabel();
        FilaRoma = new javax.swing.JLabel();
        PersonasRoma = new javax.swing.JLabel();
        TrenRoma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FilaFlorencia.setBackground(new java.awt.Color(0, 0, 0));
        FilaFlorencia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaFlorencia.setForeground(new java.awt.Color(0, 0, 0));
        FilaFlorencia.setText("0");
        getContentPane().add(FilaFlorencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 40, 30));

        PersonaFlorencia.setBackground(new java.awt.Color(0, 0, 0));
        PersonaFlorencia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PersonaFlorencia.setForeground(new java.awt.Color(0, 0, 0));
        PersonaFlorencia.setText("0");
        getContentPane().add(PersonaFlorencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 40, 30));

        TrenFlorencia.setBackground(new java.awt.Color(0, 0, 0));
        TrenFlorencia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TrenFlorencia.setForeground(new java.awt.Color(0, 0, 0));
        TrenFlorencia.setText("0");
        getContentPane().add(TrenFlorencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 40, 30));

        FilaVenicia.setBackground(new java.awt.Color(0, 0, 0));
        FilaVenicia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaVenicia.setForeground(new java.awt.Color(0, 0, 0));
        FilaVenicia.setText("0");
        getContentPane().add(FilaVenicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 40, 30));

        PersonasVenicia.setBackground(new java.awt.Color(0, 0, 0));
        PersonasVenicia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PersonasVenicia.setForeground(new java.awt.Color(0, 0, 0));
        PersonasVenicia.setText("0");
        getContentPane().add(PersonasVenicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, 30));

        TrenVenicia.setBackground(new java.awt.Color(0, 0, 0));
        TrenVenicia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TrenVenicia.setForeground(new java.awt.Color(0, 0, 0));
        TrenVenicia.setText("0");
        getContentPane().add(TrenVenicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 40, 30));

        FilaMilan.setBackground(new java.awt.Color(0, 0, 0));
        FilaMilan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaMilan.setForeground(new java.awt.Color(0, 0, 0));
        FilaMilan.setText("0");
        getContentPane().add(FilaMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 40, 30));

        PersonasMilan.setBackground(new java.awt.Color(0, 0, 0));
        PersonasMilan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PersonasMilan.setForeground(new java.awt.Color(0, 0, 0));
        PersonasMilan.setText("0");
        getContentPane().add(PersonasMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 40, 30));

        TrenMilan.setBackground(new java.awt.Color(0, 0, 0));
        TrenMilan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TrenMilan.setForeground(new java.awt.Color(0, 0, 0));
        TrenMilan.setText("0");
        getContentPane().add(TrenMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, 30));

        FilaNapoles.setBackground(new java.awt.Color(0, 0, 0));
        FilaNapoles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaNapoles.setForeground(new java.awt.Color(0, 0, 0));
        FilaNapoles.setText("0");
        getContentPane().add(FilaNapoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 30));

        PersonasNapoles.setBackground(new java.awt.Color(0, 0, 0));
        PersonasNapoles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PersonasNapoles.setForeground(new java.awt.Color(0, 0, 0));
        PersonasNapoles.setText("0");
        getContentPane().add(PersonasNapoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 30));

        TrenNapoles.setBackground(new java.awt.Color(0, 0, 0));
        TrenNapoles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TrenNapoles.setForeground(new java.awt.Color(0, 0, 0));
        TrenNapoles.setText("0");
        getContentPane().add(TrenNapoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 40, 30));

        FilaRoma.setBackground(new java.awt.Color(0, 0, 0));
        FilaRoma.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaRoma.setForeground(new java.awt.Color(0, 0, 0));
        FilaRoma.setText("0");
        getContentPane().add(FilaRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 10, 20));

        PersonasRoma.setBackground(new java.awt.Color(0, 0, 0));
        PersonasRoma.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PersonasRoma.setForeground(new java.awt.Color(0, 0, 0));
        PersonasRoma.setText("0");
        getContentPane().add(PersonasRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 10, 20));

        TrenRoma.setBackground(new java.awt.Color(0, 0, 0));
        TrenRoma.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        TrenRoma.setForeground(new java.awt.Color(0, 0, 0));
        TrenRoma.setText("0");
        getContentPane().add(TrenRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 40, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Interfaz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FilaFlorencia;
    private javax.swing.JLabel FilaMilan;
    private javax.swing.JLabel FilaNapoles;
    private javax.swing.JLabel FilaRoma;
    private javax.swing.JLabel FilaVenicia;
    private javax.swing.JLabel PersonaFlorencia;
    private javax.swing.JLabel PersonasMilan;
    private javax.swing.JLabel PersonasNapoles;
    private javax.swing.JLabel PersonasRoma;
    private javax.swing.JLabel PersonasVenicia;
    private javax.swing.JLabel TrenFlorencia;
    private javax.swing.JLabel TrenMilan;
    private javax.swing.JLabel TrenNapoles;
    private javax.swing.JLabel TrenRoma;
    private javax.swing.JLabel TrenVenicia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
