package Interfaz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author josep
 */
public class Sistemas extends javax.swing.JFrame {
Logica cambiar=new Logica();
    /**
     * Creates new form Sistemas
     */
    public Sistemas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FilaFlorencia = new javax.swing.JLabel();
        PilasDeFlorencia = new javax.swing.JLabel();
        FilaVenicia = new javax.swing.JLabel();
        PilasDeVenice = new javax.swing.JLabel();
        FilaMilan = new javax.swing.JLabel();
        PilasDeMilan = new javax.swing.JLabel();
        FilaNapoles = new javax.swing.JLabel();
        PilasDeNaples = new javax.swing.JLabel();
        FilaRoma = new javax.swing.JLabel();
        PilasDeRoma = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Tren1Texto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Tren10 = new javax.swing.JLabel();
        Tren1 = new javax.swing.JLabel();
        Tren2 = new javax.swing.JLabel();
        Tren3 = new javax.swing.JLabel();
        Tren4 = new javax.swing.JLabel();
        Tren5 = new javax.swing.JLabel();
        Tren6 = new javax.swing.JLabel();
        Tren7 = new javax.swing.JLabel();
        Tren8 = new javax.swing.JLabel();
        Tren9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FilaFlorencia.setBackground(new java.awt.Color(0, 0, 0));
        FilaFlorencia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaFlorencia.setForeground(new java.awt.Color(0, 0, 0));
        FilaFlorencia.setText("0");
        getContentPane().add(FilaFlorencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 40, 30));

        PilasDeFlorencia.setBackground(new java.awt.Color(0, 0, 0));
        PilasDeFlorencia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PilasDeFlorencia.setForeground(new java.awt.Color(0, 0, 0));
        PilasDeFlorencia.setText("0");
        getContentPane().add(PilasDeFlorencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 40, 30));

        FilaVenicia.setBackground(new java.awt.Color(0, 0, 0));
        FilaVenicia.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaVenicia.setForeground(new java.awt.Color(0, 0, 0));
        FilaVenicia.setText("0");
        getContentPane().add(FilaVenicia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 40, 30));

        PilasDeVenice.setBackground(new java.awt.Color(0, 0, 0));
        PilasDeVenice.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PilasDeVenice.setForeground(new java.awt.Color(0, 0, 0));
        PilasDeVenice.setText("0");
        getContentPane().add(PilasDeVenice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, 30));

        FilaMilan.setBackground(new java.awt.Color(0, 0, 0));
        FilaMilan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaMilan.setForeground(new java.awt.Color(0, 0, 0));
        FilaMilan.setText("0");
        getContentPane().add(FilaMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 40, 30));

        PilasDeMilan.setBackground(new java.awt.Color(0, 0, 0));
        PilasDeMilan.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PilasDeMilan.setForeground(new java.awt.Color(0, 0, 0));
        PilasDeMilan.setText("0");
        getContentPane().add(PilasDeMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 40, 30));

        FilaNapoles.setBackground(new java.awt.Color(0, 0, 0));
        FilaNapoles.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaNapoles.setForeground(new java.awt.Color(0, 0, 0));
        FilaNapoles.setText("0");
        getContentPane().add(FilaNapoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 30));

        PilasDeNaples.setBackground(new java.awt.Color(0, 0, 0));
        PilasDeNaples.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PilasDeNaples.setForeground(new java.awt.Color(0, 0, 0));
        PilasDeNaples.setText("0");
        getContentPane().add(PilasDeNaples, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 40, 30));

        FilaRoma.setBackground(new java.awt.Color(0, 0, 0));
        FilaRoma.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        FilaRoma.setForeground(new java.awt.Color(0, 0, 0));
        FilaRoma.setText("0");
        getContentPane().add(FilaRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 80, 20));

        PilasDeRoma.setBackground(new java.awt.Color(0, 0, 0));
        PilasDeRoma.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        PilasDeRoma.setForeground(new java.awt.Color(0, 0, 0));
        PilasDeRoma.setText("0");
        getContentPane().add(PilasDeRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 10, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Interfaz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        jLabel2.setText("TREN 10");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 220, 60, 20));

        jButton1.setText("Movimiento");
        jButton1.setActionCommand("Movimiento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        Tren1Texto.setText("TREN 1");
        getContentPane().add(Tren1Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 60, 20));

        jLabel4.setText("TREN 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, 60, 20));

        jLabel5.setText("TREN 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 60, 30));

        jLabel6.setText("TREN 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 60, 20));

        jLabel7.setText("TREN 5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 60, 20));

        jLabel8.setText("TREN 6");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 60, 20));

        jLabel9.setText("TREN 7");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 60, 20));

        jLabel10.setText("TREN 8");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 60, 20));

        jLabel11.setText("TREN 9");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 60, 20));

        Tren10.setText("0");
        getContentPane().add(Tren10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 50, -1));

        Tren1.setText("0");
        getContentPane().add(Tren1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, 50, -1));

        Tren2.setText("0");
        getContentPane().add(Tren2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 50, -1));

        Tren3.setText("0");
        getContentPane().add(Tren3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 50, -1));

        Tren4.setText("0");
        getContentPane().add(Tren4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 50, -1));

        Tren5.setText("0");
        getContentPane().add(Tren5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 50, -1));

        Tren6.setText("0");
        getContentPane().add(Tren6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 50, -1));

        Tren7.setText("0");
        getContentPane().add(Tren7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 50, -1));

        Tren8.setText("0");
        getContentPane().add(Tren8, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 50, -1));

        Tren9.setText("0");
        getContentPane().add(Tren9, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Arranque();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistemas().setVisible(true);
            }
        });
    }
    public void CambiarEtiqueta(String NombreDeEtiqueta,int valor){
     String dato=String.valueOf(valor);
     
      switch(NombreDeEtiqueta){
          case "Roma" -> {FilaRoma.setText(dato);}
          
          case "Napoles" -> {FilaNapoles.setText(dato);}
          
          case "Milan" -> {FilaMilan.setText(dato);}
          
          case "Venecia" -> {FilaVenicia.setText(dato);}
          
          case "Florencia" -> {FilaFlorencia.setText(dato);}
          
          //Trenes
          case "Tren1"-> {Tren1.setText(dato);} 
          
          case "Tren2"-> {Tren2.setText(dato);} 

          case "Tren3"-> {Tren3.setText(dato);} 
          
          case "Tren4"-> {Tren4.setText(dato);} 
          
          case "Tren5"-> {Tren5.setText(dato);} 
          
          case "Tren6"-> {Tren6.setText(dato);} 
          
          case "Tren7"-> {Tren7.setText(dato);} 

          case "Tren8"-> {Tren8.setText(dato);} 
          
          case "Tren9"-> {Tren9.setText(dato);} 
          
          case "Tren10"-> {Tren10.setText(dato);}   
          
          //Pilas
          case "PilaRoma"-> {PilasDeRoma.setText(dato);}
          
          case "PilaNapoles"-> {PilasDeNaples.setText(dato);}
          
          case "PilaMilan"-> {PilasDeMilan.setText(dato);}
          
          case "PilaVenecia"-> {PilasDeVenice.setText(dato);}
          
          case "PilaFlorencia"-> {PilasDeFlorencia.setText(dato);}
      }
      this.repaint();
    }
    public void Arranque(){
      cambiar.montarPersonas();
       int guardar; 
       int guardarTren;
       int GuardarPila;
       guardar=cambiar.ContarPersonas(0);
       guardarTren=cambiar.ContarTrenes(0);
       GuardarPila=cambiar.ContarPilas(2);
       CambiarEtiqueta("Roma",guardar);
       CambiarEtiqueta("Tren1",guardarTren);
       CambiarEtiqueta("PilaMilan",GuardarPila);
    }
           

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FilaFlorencia;
    private javax.swing.JLabel FilaMilan;
    private javax.swing.JLabel FilaNapoles;
    private javax.swing.JLabel FilaRoma;
    private javax.swing.JLabel FilaVenicia;
    private javax.swing.JLabel PilasDeFlorencia;
    private javax.swing.JLabel PilasDeMilan;
    private javax.swing.JLabel PilasDeNaples;
    private javax.swing.JLabel PilasDeRoma;
    private javax.swing.JLabel PilasDeVenice;
    private javax.swing.JLabel Tren1;
    private javax.swing.JLabel Tren10;
    private javax.swing.JLabel Tren1Texto;
    private javax.swing.JLabel Tren2;
    private javax.swing.JLabel Tren3;
    private javax.swing.JLabel Tren4;
    private javax.swing.JLabel Tren5;
    private javax.swing.JLabel Tren6;
    private javax.swing.JLabel Tren7;
    private javax.swing.JLabel Tren8;
    private javax.swing.JLabel Tren9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
